baseURL = "/"
languageCode = "en-us"
title = "自由.自在"
theme = "yellow"

[params]
#博客简介
description = "不再是少年"
#博客主题颜色
themeColor = "theme-base-08"

author = "杨修"
authorImage = "https://ftp.bmp.ovh/imgs/2020/09/d2c3225b7119bc23.jpg"

images = [ "https://ftp.bmp.ovh/imgs/2020/09/d2c3225b7119bc23.jpg" ]


[[menu.social]]
    name = "GitHub"
    url = "https://github.com/liyu4"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/liyu7771"
    pre = "<i class='fab fa-twitter'></i>"


[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[permalinks]
  blog = "/:year/:month/:title/"


